version: '3.8'

services:
  web:
    build: .
    container_name: minecraft-texture-web
    ports:
      - "3001:3000"
    volumes:
      - ./uploads:/app/uploads
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3 